### ISSUE TITLE
Add colour back to Icons

### ISSUE THREAD

**Issue by PureMindGames** [myst6re/makoureactor#166]
I respect that this is probably just a me issue, but the older icons were easier to find and tell appart at a glance because they were coloured.

**Comment by sithlord48** [comment]
Sorry you don't like the Icon Theme:

This is really the job of your operating system not a random application, Makou supports icon themes and like any good application will use the ones set by system if has support for them. If the system does not support [XDG Icon Themes](https://www.freedesktop.org/wiki/Specifications/icon-theme-spec/) you will get a the fallback theme. The fallback theme is really two themes one for light themed and one for dark themed systems. The fallback icons can be improved but would need to be readable on various backgrounds as well as in svg format so they can be scaled correct for the users DPI. We used alot of icons from [KDE Breeze](https://develop.kde.org/frameworks/breeze-icons/). That we use was much easier since  it contains almost all the icons we need and correctly named for the xdg theme. it left us with very few png and non theme responsive icons.

Starting Maximized

Makou Reactor is saving its geometry when you close it so if you close it maximized it should start back up that way. However the application can only ask the system to put it there at start up and the system can refuse and do its own thing

**Comment by PureMindGames** [comment]
Icons
[<a href="https://imgbb.com/"><img src="https://i.ibb.co/WfG65W9/Untitled.png" alt="Untitled" border="0"></a>](url) If it's a system thing shouldn't I see the more regonisable(and in my opinion more readable(I can't be the only one who looked at the 'Open' icon(when I eventually found it) and went "What's this do?") old icons? Is there a way to put them in? I have the apps theme set to System.

Start Maximised
But the current Continuos is the only version that doesn't save the maximised view, I even have an older Continous build and that opens maximised.

**Comment by myst6re** [comment]
We can sure find a better open icon, as I am not a big fan of the breeze icon for "open file". The thing is we try to uniformize icons, and KDE breeze was one easy option. Unfortunately it doesn't give a lot of choices (https://cdn.kde.org/breeze-icons/icons.html)

I can sacrifice consitency a little and use system icons when available (on windows this affects the open icon, and warning/error/fatal)

**Comment by sithlord48** [comment]
> If it's a system thing shouldn't I see the more regonisable

Yes if your system support XDG Icon themes. (Windows does not support this standard last i checked) 

> But the current Continuos is the only version that doesn't save the maximised view, I even have an older Continous build and that opens maximised.

Then the bug has been fixed (i only ever test continuous for bugs) 

The icons can be replaced with any other icons however the new icons should be SVG format and have a light and a dark theme  or work with any background color. All you need to make them is inkscape and some time

**Comment by PureMindGames** [comment]
That's weird, I just downloaded the latest and it still doesn't do it for me, I have 2 other continuos builds one I downloaded on 19/01/2023 and one from 25/08/2022 and only the 25/08/2022 opens maximised.

**Comment by myst6re** [comment]
Do you have a file named "Makou_Reactor.ini" after the first launch? Can you copy the contents of it here, after you closed Makou in maximized mode?

**Comment by PureMindGames** [comment]
[General]
varFile=F:/Documents Backup/Final Fantasy VII Mod Tools/makoureactor-2.0.0-win64/vars.cfg
lang=@Invalid()
windowState=@ByteArray(\0\0\0\xff\0\0\0\0\xfd\0\0\0\0\0\0\x2\xa1\0\0\x1o\0\0\0\x4\0\0\0\x4\0\0\0\b\0\0\0\b\xfc\0\0\0\x1\0\0\0\x2\0\0\0\x1\0\0\0\xe\0t\0o\0o\0l\0\x62\0\x61\0r\x1\0\0\0\0\xff\xff\xff\xff\0\0\0\0\0\0\0\0)
windowGeometry=@ByteArray(\x1\xd9\xd0\xcb\0\x3\0\0\0\0\x3\\\0\0\x1\xb7\0\0\x5\xfc\0\0\x3v\0\0\0\0\0\0\0\0\xff\xff\xff\xfe\xff\xff\xff\xfe\0\0\0\0\x2\0\0\0\a\x80\0\0\x3\\\0\0\x1\xd6\0\0\x5\xfc\0\0\x3v)
horizontalSplitterState=@ByteArray(\0\0\0\xff\0\0\0\x1\0\0\0\x2\0\0\0\xbc\0\0\0v\x1\xff\xff\xff\xff\x1\0\0\0\x2\0)
verticalSplitterState=@ByteArray(\0\0\0\xff\0\0\0\x1\0\0\0\x2\0\0\0v\0\0\x2&\x1\xff\xff\xff\xff\x1\0\0\0\x1\0)
fieldListVisible=true
backgroundVisible=true
fieldListSortColumn=1
fieldListSortOrder=0
grpToolbarVisible=true
scriptToolbarVisible=true

I've even tried copy pasting the 'window state' and 'window geometry' lines from 1.8.6 and the Continuos that opens maximised ini files but it didn't work.

**Comment by myst6re** [comment]
Your file seems correct, and you're right, windowState and windowGeometry are responsible for the maximized state.

So I assume that's an issue with Qt, we'll try to reproduce the issue on Windows and see if something can be done (upgrading Qt or else)

**Comment by PureMindGames** [comment]
For referrence this is the ini from the one that opens maximised

[General]
varFile=F:/Documents Backup/Final Fantasy VII Mod Tools/makoureactor-2.0.0/vars.cfg
lang=@Invalid()
open_path=E:/SteamLibrary/steamapps/common/FINAL FANTASY VII/data/field
open_path_selected_filter=0
recentFiles=E:/SteamLibrary/steamapps/common/FINAL FANTASY VII/data/field/flevel.lgp
currentField=blin62_3
windowState=@ByteArray(\0\0\0\xff\0\0\0\0\xfd\0\0\0\0\0\0\a\x80\0\0\x3\xc9\0\0\0\x4\0\0\0\x4\0\0\0\b\0\0\0\b\xfc\0\0\0\x1\0\0\0\x2\0\0\0\x1\0\0\0\xe\0t\0o\0o\0l\0\x62\0\x61\0r\x1\0\0\0\0\xff\xff\xff\xff\0\0\0\0\0\0\0\0)
windowGeometry=@ByteArray(\x1\xd9\xd0\xcb\0\x3\0\0\0\0\0\0\xff\xff\xff\xf8\0\0\a\x7f\0\0\x4\xf\0\0\x2\x80\0\0\x1\x18\0\0\x5 \0\0\x2\xb6\0\0\0\0\x2\0\0\0\a\x80\0\0\0\0\0\0\0\x17\0\0\a\x7f\0\0\x4\xf)
horizontalSplitterState=@ByteArray(\0\0\0\xff\0\0\0\x1\0\0\0\x2\0\0\0\xbc\0\0\0v\x1\xff\xff\xff\xff\x1\0\0\0\x2\0)
verticalSplitterState=@ByteArray(\0\0\0\xff\0\0\0\x1\0\0\0\x2\0\0\0v\0\0\x2&\x1\xff\xff\xff\xff\x1\0\0\0\x1\0)
fieldListVisible=true
backgroundVisible=true
fieldListSortColumn=1
fieldListSortOrder=0
grpToolbarVisible=true
scriptToolbarVisible=true
dispUnusedText=true

**Comment by myst6re** [comment]
I modified the open icon
![2023-02-07 22_07_16-Window](https://user-images.githubusercontent.com/8015696/217365746-de3e880a-c55f-4cd1-a0ba-2d376f31b3d2.png)
